attn_mode = "flash"
blocks_to_swap = 0
cache_llm_adapter_outputs = true
caption_dropout_rate = 0.0
checkpointing_epochs = 1
dataloader_pin_memory = true
dataset_config = "/home/scv/nvme0n1p1/训练器相关/anima缓存/rokkotsu_goddess_528_7tag3nl-20260528-020030-retry-20260528-024840/dataset.runtime.toml"
discrete_flow_shift = 1.0
drop_lowres_images = true
gradient_accumulation_steps = 1
gradient_checkpointing = false
learning_rate = 2e-5
log_every_n_steps = 1
logging_dir = "/home/scv/nvme0n1p1/训练器相关/anima缓存/rokkotsu_goddess_528_7tag3nl-20260528-020030-retry-20260528-024840/model_cache/logs"
lora_cache_dir = "/home/scv/nvme0n1p1/训练器相关/anima缓存/rokkotsu_goddess_528_7tag3nl-20260528-020030-retry-20260528-024840/dataset_cache/dataset-01/lora"
lr_scheduler = "lulu_loss_gated_cosine"
lr_warmup_steps = 500
masked_loss = true
max_grad_norm = 1.0
max_train_epochs = 6
max_train_steps = 0
min_pixels = 500000
mixed_precision = "bf16"
network_alpha = 32
network_dim = 32
network_module = "networks.lora_anima"
network_train_unet_only = true
optimizer_args = [ "weight_decay=0.01", "eps=1e-8", "betas=0.9,0.99",]
optimizer_type = "AdamW"
output_dir = "/home/scv/nvme0n1p1/训练器相关/anima缓存/rokkotsu_goddess_528_7tag3nl-20260528-020030-retry-20260528-024840/training_output"
output_name = "rokkotsu_goddess_5_14"
path_pattern = "*"
persistent_data_loader_workers = true
pretrained_model_name_or_path = "/home/scv/nvme0n1p1/ComfyUI/models/diffusion_models/anima/anima-preview3-base.safetensors"
qwen3 = "/home/scv/nvme0n1p1/ComfyUI/models/text_encoders/anima/anima_qwen_3_06b_base.safetensors"
resized_image_dir = "/home/scv/nvme0n1p1/训练器相关/anima缓存/rokkotsu_goddess_528_7tag3nl-20260528-020030-retry-20260528-024840/dataset_cache/dataset-01/resized"
sample_every_n_epochs = 1
sample_prompts = "configs/sample-prompts/imported/rokkotsu_goddess_528_7tag3nl.txt"
sample_sampler = "euler"
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "bf16"
sigmoid_bias = 0.0
skip_cache_check = true
source_image_dir = "/home/scv/图片/安/5-14"
timestep_sampling = "sigmoid"
torch_compile = true
train_batch_size = 1
unsloth_offload_checkpointing = false
use_cmmd = false
use_custom_down_autograd = true
use_text_cache = true
use_vae_cache = true
vae = "/home/scv/nvme0n1p1/ComfyUI/models/vae/anima/anima_vae.safetensors"
vae_chunk_size = 64
vae_disable_cache = true
