"""Delegated queue service methods."""

from __future__ import annotations

from web.services.training import queue_control as _queue_control_impl
from web.services.training import queue_dispatch as _queue_dispatch_impl
from web.services.training import queue_enqueue as _queue_enqueue_impl
from web.services.training import queue_state as _queue_state_impl


start_queue_on_startup = _queue_state_impl.start_queue_on_startup
get_queue_snapshot = _queue_state_impl.get_queue_snapshot
_repair_queue_on_startup = _queue_state_impl._repair_queue_on_startup
_normalize_queue = _queue_state_impl._normalize_queue
_queue_items = _queue_state_impl._queue_items
_find_queue_item = _queue_state_impl._find_queue_item
_update_queue_item = _queue_state_impl._update_queue_item
_attach_history_task_to_queue_item = _queue_state_impl._attach_history_task_to_queue_item
_queue_history_meta = _queue_state_impl._queue_history_meta
_compact_queue = _queue_state_impl._compact_queue
_save_queue = _queue_state_impl._save_queue
_broadcast_queue = _queue_state_impl._broadcast_queue

enqueue_training = _queue_enqueue_impl.enqueue_training
enqueue_training_batch = _queue_enqueue_impl.enqueue_training_batch
enqueue_resume_from_history_task = _queue_enqueue_impl.enqueue_resume_from_history_task
_clone_queue_item_for_retry = _queue_enqueue_impl._clone_queue_item_for_retry

move_queue_item = _queue_control_impl.move_queue_item
cancel_queue_item = _queue_control_impl.cancel_queue_item
retry_queue_item = _queue_control_impl.retry_queue_item
cancel_waiting_queue_items = _queue_control_impl.cancel_waiting_queue_items
cancel_all_queue_items = _queue_control_impl.cancel_all_queue_items
abort_queue_after_current = _queue_control_impl.abort_queue_after_current
force_abort_queue = _queue_control_impl.force_abort_queue
clear_finished_queue_items = _queue_control_impl.clear_finished_queue_items
clear_completed_queue_items = _queue_control_impl.clear_completed_queue_items
clear_canceled_queue_items = _queue_control_impl.clear_canceled_queue_items
clear_queue_items_by_state = _queue_control_impl.clear_queue_items_by_state
set_queue_settings = _queue_control_impl.set_queue_settings
set_queue_paused = _queue_control_impl.set_queue_paused

_schedule_queue_dispatch = _queue_dispatch_impl._schedule_queue_dispatch
_dispatch_queue = _queue_dispatch_impl._dispatch_queue
_pause_queue_after_failure = _queue_dispatch_impl._pause_queue_after_failure
_start_queue_item = _queue_dispatch_impl._start_queue_item
_ensure_queue_resume_checkpoint_exists = _queue_dispatch_impl._ensure_queue_resume_checkpoint_exists
_queue_resume_runtime_config_file = _queue_dispatch_impl._queue_resume_runtime_config_file
_queue_item_runtime = _queue_dispatch_impl._queue_item_runtime
