attn_mode = "flash"
blocks_to_swap = 0
cache_latents = true
cache_latents_to_disk = true
cache_llm_adapter_outputs = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
caption_dropout_rate = 0.0
checkpointing_epochs = 1
dataloader_pin_memory = true
dataset_config = "configs/datasets/rokkotsu_goddess_5_14.toml"
discrete_flow_shift = 1.0
gradient_accumulation_steps = 1
gradient_checkpointing = true
learning_rate = 2e-5
log_every_n_steps = 1
lora_cache_dir = "/home/scv/图片/安/5-15-b"
lr_scheduler = "linear"
lr_warmup_steps = 500
masked_loss = true
max_grad_norm = 1.0
max_train_epochs = 16
mixed_precision = "bf16"
network_alpha = 32
network_dim = 32
network_module = "networks.lora_anima"
network_train_unet_only = true
optimizer_args = [ "weight_decay=0.01", "eps=1e-8", "betas=0.9,0.99",]
optimizer_type = "AdamW"
output_dir = "/home/scv/sda1/DiffPipeForge2/output/肋骨女神/mylora"
output_name = "rokkotsu_goddess_5_14"
persistent_data_loader_workers = true
pretrained_model_name_or_path = "/home/scv/nvme0n1p1/ComfyUI/models/diffusion_models/anima/anima-preview3-base.safetensors"
qwen3 = "/home/scv/nvme0n1p1/ComfyUI/models/text_encoders/anima/anima_qwen_3_06b_base.safetensors"
resized_image_dir = "/home/scv/图片/安/5-15-a"
sample_every_n_epochs = 1
sample_prompts = "configs/sample_prompts.txt"
sample_sampler = "euler"
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "bf16"
skip_cache_check = true
source_image_dir = "/home/scv/图片/安/5-14"
static_token_count = 4096
timestep_sampling = "sigmoid"
torch_compile = true
train_batch_size = 1
trim_crossattn_kv = false
use_custom_down_autograd = true
vae = "/home/scv/nvme0n1p1/ComfyUI/models/vae/anima/anima_vae.safetensors"
vae_chunk_size = 64
vae_disable_cache = true
