"""Anima DirectEdit node.

Image in, edited LATENT out. Consumes ComfyUI's stock ``MODEL`` / ``CLIP`` /
``VAE`` sockets - pipe in the same loaders you'd use for a normal Anima
KSampler workflow (``UNETLoader``/``CLIPLoader``/``VAELoader`` or
``CheckpointLoaderSimple``). The tagger socket comes from the
``comfyui-anima-tagger`` package (``AnimaTaggerLoader``) - install it
alongside this package if you want on-image psi_src derivation; otherwise
use ``prompt_src_override`` to supply psi_src directly.

Pipeline mirrors ``scripts/edit.py``:

  IMAGE -> PIL                        (ComfyUI [B,H,W,C] in [0,1] -> PIL.RGB)
  tagger.predict_caption -> psi_src   (skipped if prompt_src_override is set;
                                       tagger comes from AnimaTaggerLoader in
                                       comfyui-anima-tagger)
  psi_tar = psi_src + ", " + edit_text
  bucket pick from source aspect ratio
  CLIP.tokenize / encode_from_tokens(return_dict=True) for psi_src/tar/neg
  diffusion_model.preprocess_text_embeds -> 512-padded crossattn embeds
  VAE.encode + process_latent_in       -> standardized z_clean (DiT input space)
  invert(z_clean, embed_src)           -> z_inv, delta_z
  edit_forward(z_inv[0], delta_z, ...) -> z_edit (still standardized)
  process_latent_out                   -> raw VAE-space LATENT (comfy convention)
"""

from __future__ import annotations

import importlib
import logging
import sys
from pathlib import Path
from typing import Tuple

import numpy as np
import torch

# Resolve where to import ``library.*`` from.
#
# Two install shapes are supported:
#
# 1. **Inside the anima_lora repo** (dev / monorepo install). This file lives
#    at ``anima_lora/custom_nodes/comfyui-anima-directedit/nodes.py`` so
#    ``parents[1]`` of HERE is the repo root, and the live ``library/`` is
#    reachable.
# 2. **Standalone ComfyUI install** (just dropped this folder into
#    ``ComfyUI/custom_nodes/``). Then ``parents[1]`` is ``ComfyUI/custom_nodes/``
#    which has no ``library/`` - fall back to the bundled inference subset
#    under ``_vendor/``. The vendor tree is generated by
#    ``scripts/sync_vendor.py`` in the parent repo and ships with the
#    published node version.
HERE = Path(__file__).resolve().parent
ANIMA_LORA = HERE.parents[1]
VENDOR = HERE / "_vendor"


def _resolve_anima_modules():
    """Return the live ``library`` modules if reachable, else the bundled
    vendor copies. Vendor wins only when the live import fails - in-repo
    edits to ``library/...`` are picked up automatically during development."""
    if str(ANIMA_LORA) not in sys.path:
        sys.path.insert(0, str(ANIMA_LORA))

    def _imports():
        anima_tagger = importlib.import_module("library.captioning.anima_tagger")
        buckets_mod = importlib.import_module("library.datasets.buckets")
        directedit_mod = importlib.import_module("library.inference.directedit")
        sampling_mod = importlib.import_module("library.inference.sampling")
        dispatcher_mod = importlib.import_module("library.inference.edit_dispatcher")
        splice_mod = importlib.import_module("library.inference.directedit_splice")
        return (
            anima_tagger, buckets_mod, directedit_mod, sampling_mod,
            dispatcher_mod, splice_mod,
        )

    try:
        return _imports()
    except ImportError:
        if not VENDOR.exists():
            raise
        if str(VENDOR) not in sys.path:
            sys.path.insert(0, str(VENDOR))
        # Drop any partially-imported modules so the vendor tree's copies
        # actually load (the live attempt may have cached half a tree).
        for k in [
            k for k in list(sys.modules)
            if k.startswith(("library.", "networks."))
            or k in ("library", "networks")
        ]:
            del sys.modules[k]
        return _imports()


from PIL import Image  # noqa: E402

import comfy.model_management  # noqa: E402  ComfyUI module; only resolvable inside ComfyUI
import comfy.utils  # noqa: E402  ComfyUI module; only resolvable inside ComfyUI

(
    _anima_tagger_mod,
    _buckets_mod,
    directedit,
    inference_utils,
    _dispatcher_mod,
    _splice_mod,
) = _resolve_anima_modules()
AnimaTagger = _anima_tagger_mod.AnimaTagger
CONSTANT_TOKEN_BUCKETS = _buckets_mod.CONSTANT_TOKEN_BUCKETS
derive_target_caption = _dispatcher_mod.derive_target_caption
splice_crossattn_emb = _splice_mod.splice_crossattn_emb

# T5 (T5xxl) PAD token id is 0 across the T5 family; vendor doesn't bundle the
# T5 tokenizer config so we hardcode rather than `load_t5_tokenizer().pad_token_id`.
_T5_PAD_ID = 0

logger = logging.getLogger(__name__)


def _pick_bucket(pil_img: Image.Image) -> Tuple[int, int]:
    """Closest CONSTANT_TOKEN_BUCKETS entry by aspect ratio. Returns (H, W)."""
    rw, rh = pil_img.size
    target = rw / rh
    best = min(CONSTANT_TOKEN_BUCKETS, key=lambda wh: abs(wh[0] / wh[1] - target))
    return best[1], best[0]  # bucket is (W, H); we return (H, W)


def _comfy_image_to_pil(image_tensor: torch.Tensor) -> Image.Image:
    """ComfyUI IMAGE [B, H, W, C] in [0,1] -> PIL.RGB (first batch element)."""
    arr = image_tensor[0].clamp(0, 1).cpu().numpy()
    return Image.fromarray((arr * 255).astype(np.uint8)).convert("RGB")


def _pil_to_comfy_image(pil_img: Image.Image) -> torch.Tensor:
    """PIL.RGB -> ComfyUI IMAGE [1, H, W, 3] in [0,1] (for VAE.encode input)."""
    arr = np.asarray(pil_img.convert("RGB"), dtype=np.float32) / 255.0
    return torch.from_numpy(arr).unsqueeze(0)


def _encode_prompt_comfy(
    clip, unet, text: str, device: torch.device, dtype: torch.dtype
) -> Tuple[torch.Tensor, torch.Tensor]:
    """Tokenize + encode + LLMAdapter preprocess via the comfy CLIP socket.

    Mirrors ``model_base.Anima.extra_conds``: tokenize through the comfy
    Anima tokenizer, encode Qwen3 hidden states + collect t5xxl ids/weights,
    then run the DiT's ``preprocess_text_embeds`` (LLMAdapter + 512 pad)
    once. Verified to produce embeddings within numerical noise of the
    library's ``prepare_text_inputs`` for the prompts we feed DirectEdit.

    Returns ``(embed, t5xxl_ids_512)`` — the 512-padded crossattn tensor and
    the 1-D T5 ids right-padded to 512 with the T5 pad id. Both are needed
    for slot-surgery to align span endpoints with crossattn slot indices.
    """
    tokens = clip.tokenize(text)
    out = clip.encode_from_tokens(tokens, return_pooled=False, return_dict=True)
    cond = out["cond"]  # [1, T_q, 1024]
    t5xxl_ids = out["t5xxl_ids"]  # [T_t5]
    t5xxl_weights = out["t5xxl_weights"]  # [T_t5]

    # Mirror model_base.Anima.extra_conds shape conventions.
    t5xxl_ids = t5xxl_ids.unsqueeze(0).to(device)  # [1, T_t5]
    t5xxl_weights = t5xxl_weights.unsqueeze(0).unsqueeze(-1).to(device, dtype=dtype)
    cond = cond.to(device, dtype=dtype)

    embed = unet.preprocess_text_embeds(cond, t5xxl_ids, t5xxl_weights=t5xxl_weights)

    # Pad T5 ids out to embed.shape[1] (512) with the T5 pad id so splice
    # invariants line up — preprocess_text_embeds 0-pads crossattn, we 0-pad
    # the IDs alongside it.
    t_emb = embed.shape[1]
    if t5xxl_ids.shape[1] < t_emb:
        pad_n = t_emb - t5xxl_ids.shape[1]
        t5xxl_ids = torch.nn.functional.pad(t5xxl_ids, (0, pad_n), value=_T5_PAD_ID)
    elif t5xxl_ids.shape[1] > t_emb:
        t5xxl_ids = t5xxl_ids[:, :t_emb]
    return embed, t5xxl_ids


_QWEN3_PAD_ID = 151643  # see comfy/text_encoders/anima.py::Qwen3Tokenizer


def _comfy_encode_last_pooled(clip, phrases: list[str]) -> torch.Tensor:
    """Dispatcher's ``EncodeLastPooledFn`` over the comfy ``CLIP`` socket.

    Naive approach (one ``clip.encode_from_tokens`` per phrase) makes comfy's
    ``CLIP.load_model`` fire N+1 times — each call logs "Model AnimaTEModel_
    prepared for dynamic VRAM loading" and re-walks the patcher, which spams
    the terminal and is needlessly slow on long captions.

    Instead we:
      1. Tokenize each phrase (CPU-only).
      2. Pad all chunks to the longest length with the Qwen3 pad token
         (151643). The mask logic in ``SDClipModel.process_tokens`` treats
         pad as EOS — masked attention from the first pad onward — so each
         row's "last non-pad" index is well-defined.
      3. ``comfy.model_management.load_models_gpu(...)`` once.
      4. Call the bare ``Qwen3_06BModel`` (``clip.cond_stage_model.qwen3_06b``)
         once on the (N+1, T) batch. The wrapper ``encode_token_weights``
         concatenates rows along the time dim — bypass it.
      5. For each row, slice the actual last non-pad token by its tokenized
         length.

    Same Qwen3 last-hidden-state semantics as the probe — just batched.
    """
    qwen3_tok = clip.tokenizer.qwen3_06b
    chunks: list[list[tuple]] = []
    seq_lens: list[int] = []
    for phrase in phrases:
        # Tokenizer config: pad_to_max_length=False, min_length=1, no
        # start/end tokens — one chunk per short phrase. Tag-length phrases
        # never spill into multi-chunk; assert defensively.
        tw = qwen3_tok.tokenize_with_weights(phrase, return_word_ids=False)
        if len(tw) != 1:
            raise RuntimeError(
                f"comfy qwen3 tokenizer produced {len(tw)} chunks for "
                f"phrase {phrase!r}; dispatcher assumes 1. Phrase too long?"
            )
        chunk = list(tw[0])
        chunks.append(chunk)
        seq_lens.append(len(chunk))

    max_len = max(seq_lens) if seq_lens else 0
    for i, chunk in enumerate(chunks):
        if len(chunk) < max_len:
            chunks[i] = chunk + [(_QWEN3_PAD_ID, 1.0)] * (max_len - len(chunk))

    comfy.model_management.load_models_gpu([clip.patcher])
    qwen3 = clip.cond_stage_model.qwen3_06b
    qwen3.set_clip_options({"execution_device": clip.patcher.load_device})
    # forward() returns (z, pooled[, extra]); z has shape (B=N+1, T, D).
    result = qwen3(chunks)
    z = result[0].float()
    qwen3.reset_clip_options()

    vecs: list[torch.Tensor] = []
    for i, seqlen in enumerate(seq_lens):
        # seqlen-1 is the last real (non-pad) position. SDClipModel.process_tokens
        # already masks attention from the first pad onward, so column index
        # seqlen-1 is the genuine last Qwen3 hidden state for this phrase.
        idx = max(seqlen - 1, 0)
        vecs.append(z[i, idx])
    return torch.stack(vecs, dim=0)


class AnimaDirectEdit:
    """Image + tag-to-add -> edited image, driven by stock MODEL/CLIP/VAE sockets."""

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "model": ("MODEL", {"tooltip": "Anima DiT (e.g. UNETLoader)."}),
                "clip": ("CLIP", {"tooltip": "Anima CLIP (Qwen3 06B + T5xxl tokenizer)."}),
                "vae": ("VAE", {"tooltip": "Qwen Image VAE."}),
                "image": ("IMAGE",),
                "edit_text": (
                    "STRING",
                    {
                        "multiline": True,
                        "default": "double peace",
                        "tooltip": (
                            "Tag(s) to add to the source caption. "
                            "psi_tar = psi_src + ', ' + edit_text. Leave "
                            "empty to use psi_src as-is (sanity-check; "
                            "should reconstruct the source)."
                        ),
                    },
                ),
                "negative_prompt": (
                    "STRING",
                    {"multiline": True, "default": "worst quality"},
                ),
                "infer_steps": ("INT", {"default": 20, "min": 1, "max": 200}),
                "flow_shift": (
                    "FLOAT",
                    {"default": 1.0, "min": 0.1, "max": 10.0, "step": 0.05},
                ),
                "guidance_scale": (
                    "FLOAT",
                    {
                        "default": 2.0,
                        "min": 1.0,
                        "max": 20.0,
                        "step": 0.1,
                        "tooltip": "CFG scale for the edit (target) pass.",
                    },
                ),
                "invert_guidance": (
                    "FLOAT",
                    {
                        "default": 1.0,
                        "min": 1.0,
                        "max": 20.0,
                        "step": 0.1,
                        "tooltip": (
                            "CFG scale during inversion. Default 1.0 (no CFG); "
                            "raise only if the inverted noise must match a "
                            "high-CFG generation seed."
                        ),
                    },
                ),
                "t_inj": (
                    "INT",
                    {
                        "default": 6,
                        "min": 0,
                        "max": 200,
                        "tooltip": (
                            "Number of early steps to inject src self-attn V "
                            "into the tar pass (paper Eq. 13). 0 = pure "
                            "deltaZ-anchored edit. Typical: t_inj ~ T/10..T/3 "
                            "(e.g. 3..9 at infer_steps=28). Higher = stronger "
                            "source-feature preservation, weaker edit "
                            "leverage. Injects at all DiT blocks except the "
                            "final (SD3.5-style default)."
                        ),
                    },
                ),
            },
            "optional": {
                "tagger": (
                    "ANIMA_TAGGER",
                    {
                        "tooltip": (
                            "AnimaTagger from AnimaTaggerLoader (in the "
                            "comfyui-anima-tagger package). Required unless "
                            "prompt_src_override is set."
                        ),
                    },
                ),
                "prompt_src_override": (
                    "STRING",
                    {
                        "multiline": True,
                        "default": "",
                        "tooltip": (
                            "Optional: replace the tagger's caption with your "
                            "own psi_src. Leave empty to use the tagger output. "
                            "Useful when the source is an Anima-generated image "
                            "and you already know the original prompt. If set, "
                            "the tagger socket is ignored."
                        ),
                    },
                ),
                "use_dispatcher": (
                    "BOOLEAN",
                    {
                        "default": True,
                        "tooltip": (
                            "Run the smart-edit dispatcher: explicit '-X' / "
                            "'no X' (matching an existing tag) does REMOVE; "
                            "Qwen3 last-pool cosine fires REPLACE on confident "
                            "matches; otherwise APPEND (= legacy behaviour). "
                            "Off = always APPEND. Adds N+1 short encode "
                            "passes through the CLIP socket."
                        ),
                    },
                ),
                "replace_threshold": (
                    "FLOAT",
                    {
                        "default": 0.92,
                        "min": 0.5,
                        "max": 1.0,
                        "step": 0.01,
                        "tooltip": (
                            "Dispatcher REPLACE gate: top-1 cosine must "
                            "exceed this. Tuned against scripts/probes/"
                            "edit_nearest_tag.py."
                        ),
                    },
                ),
                "replace_gap": (
                    "FLOAT",
                    {
                        "default": 0.04,
                        "min": 0.0,
                        "max": 0.5,
                        "step": 0.005,
                        "tooltip": (
                            "Dispatcher REPLACE gate: top1-top2 cosine gap "
                            "must exceed this. Probe ambiguous near-ties "
                            "sit at gap<0.01 and abstain into APPEND."
                        ),
                    },
                ),
                "use_slot_surgery": (
                    "BOOLEAN",
                    {
                        "default": False,
                        "tooltip": (
                            "Build embed_tar by transplanting only the "
                            "T5-diff-span slots of psi_tar's crossattn_emb "
                            "into psi_src's encoding. Off by default. "
                            "Untouched slots come from psi_src — see "
                            "library/inference/directedit_splice.py."
                        ),
                    },
                ),
            },
        }

    RETURN_TYPES = ("LATENT", "STRING", "STRING")
    RETURN_NAMES = ("latent", "prompt_src", "prompt_tar")
    FUNCTION = "edit"
    CATEGORY = "anima"
    DESCRIPTION = (
        "DirectEdit (Yang & Ye arXiv:2605.02417) editor for Anima. Runs the "
        "AnimaTagger on the source image to derive psi_src, appends edit_text "
        "to form psi_tar, then performs flow inversion + delta_z-anchored "
        "resampling on the MODEL/CLIP/VAE sockets you wire in. Returns the "
        "edited LATENT in the comfy convention (raw VAE space) - wire it "
        "into VAEDecode to render."
    )

    def edit(
        self,
        model,
        clip,
        vae,
        image: torch.Tensor,
        edit_text: str,
        negative_prompt: str,
        infer_steps: int,
        flow_shift: float,
        guidance_scale: float,
        invert_guidance: float,
        t_inj: int = 0,
        tagger: AnimaTagger | None = None,
        prompt_src_override: str = "",
        use_dispatcher: bool = True,
        replace_threshold: float = 0.92,
        replace_gap: float = 0.04,
        use_slot_surgery: bool = False,
    ):
        device = comfy.model_management.get_torch_device()
        dtype = torch.bfloat16

        pil_src = _comfy_image_to_pil(image)

        if prompt_src_override.strip():
            psi_src = prompt_src_override.strip()
            logger.info("DirectEdit: using prompt_src_override: %r", psi_src)
        else:
            if tagger is None:
                raise ValueError(
                    "AnimaDirectEdit needs either a `tagger` socket "
                    "(from AnimaTaggerLoader in the comfyui-anima-tagger "
                    "package) or a non-empty `prompt_src_override` to "
                    "derive psi_src."
                )
            logger.info("DirectEdit: running AnimaTagger from %s", tagger.ckpt_dir)
            psi_src = tagger.predict_caption(pil_src)
            logger.info("DirectEdit: psi_src = %r", psi_src)

        edit = (edit_text or "").strip()
        if edit and use_dispatcher:
            plan = derive_target_caption(
                psi_src,
                edit,
                encode_last_pooled=lambda phrases: _comfy_encode_last_pooled(
                    clip, phrases,
                ),
                replace_threshold=replace_threshold,
                replace_gap=replace_gap,
            )
            psi_tar = plan.tar_caption
            logger.info(plan.log_line())
        else:
            psi_tar = f"{psi_src}, {edit}" if edit else psi_src
        logger.info("DirectEdit: psi_tar = %r", psi_tar)

        if use_slot_surgery and not psi_src.strip():
            raise ValueError(
                "use_slot_surgery requires a non-empty psi_src — surgery "
                "transplants from the source encoding."
            )

        h_pix, w_pix = _pick_bucket(pil_src)
        pil_src_resized = pil_src.resize((w_pix, h_pix), Image.LANCZOS)
        logger.info(
            "DirectEdit: bucket %dx%d (HxW) for source aspect %.3f",
            h_pix, w_pix, pil_src.size[0] / pil_src.size[1],
        )

        # Bring DiT onto device so preprocess_text_embeds (LLMAdapter) and the
        # invert/edit forwards see resident weights. ComfyUI's patcher owns
        # eviction - we don't move it back.
        comfy.model_management.load_models_gpu([model])
        unet = model.model.diffusion_model

        with torch.no_grad():
            embed_src, t5_ids_src = _encode_prompt_comfy(
                clip, unet, psi_src, device, dtype,
            )
            embed_tar, t5_ids_tar = _encode_prompt_comfy(
                clip, unet, psi_tar, device, dtype,
            )
            embed_neg, _ = _encode_prompt_comfy(
                clip, unet, negative_prompt, device, dtype,
            )

        if use_slot_surgery:
            embed_tar_full = embed_tar
            embed_tar, span = splice_crossattn_emb(
                crossattn_emb_src=embed_src,
                crossattn_emb_tar=embed_tar_full,
                t5_ids_src=t5_ids_src,
                t5_ids_tar=t5_ids_tar,
                pad_id=_T5_PAD_ID,
            )
            logger.info(
                "DirectEdit slot surgery: diff span src[%d:%d] -> tar[%d:%d] "
                "(src_len=%d tar_len=%d suffix_len=%d)",
                span.start, span.src_end, span.start, span.tar_end,
                span.src_len, span.tar_len, span.suffix_len,
            )

        # Diagnostic: if psi_src and psi_tar collapse to the same embedding, the
        # edit pass will reconstruct the source by design (deltaz anchors + same
        # velocity field == identity). Big abs-mean diff = encoder is doing
        # its job; near-zero = encoder path is the bug.
        with torch.no_grad():
            d_st = (embed_src.float() - embed_tar.float()).abs().mean().item()
            d_sn = (embed_src.float() - embed_neg.float()).abs().mean().item()
            d_tn = (embed_tar.float() - embed_neg.float()).abs().mean().item()
        logger.info(
            "DirectEdit embed diffs (abs mean): "
            "|src-tar|=%.6f  |src-neg|=%.6f  |tar-neg|=%.6f  "
            "(src.norm=%.3f tar.norm=%.3f shape=%s)",
            d_st, d_sn, d_tn,
            embed_src.float().norm().item(),
            embed_tar.float().norm().item(),
            tuple(embed_src.shape),
        )
        if d_st < 1e-4:
            logger.warning(
                "DirectEdit: |src-tar| < 1e-4 - embeddings are effectively "
                "identical, edit pass will reconstruct the source. Check "
                "psi_src/psi_tar strings (logged above) - likely the tagger "
                "produced an empty/identical caption to edit_text."
            )

        logger.info("DirectEdit: encoding source image via VAE")
        img_in = _pil_to_comfy_image(pil_src_resized)
        z_clean = vae.encode(img_in)  # [1, C_lat, T=1, H/8, W/8]  RAW VAE latent
        # Anima DiT was trained on standardized latents (per-channel (z - mean) / std);
        # comfy's KSampler applies this via samplers.py::process_latent_in, but we call
        # the diffusion_model directly and must do it ourselves. Without this the model
        # sees out-of-distribution inputs and emits ~zero velocity, so the deltaz-anchored
        # Euler step reconstructs the source regardless of t_inj / guidance_scale.
        z_clean = model.model.process_latent_in(z_clean)
        z_clean = z_clean.to(device, dtype=dtype)
        logger.info("DirectEdit: encoded source latent %s", tuple(z_clean.shape))

        timesteps, sigmas = inference_utils.get_timesteps_sigmas(
            infer_steps, flow_shift, device
        )
        sigmas = sigmas.to(device)

        logger.info(
            "DirectEdit: invert (T=%d, src_guidance=%.2f) -> edit "
            "(tar_guidance=%.2f, t_inj=%d)",
            infer_steps, invert_guidance, guidance_scale, t_inj,
        )
        # Two-phase progress bar: invert occupies [0, T), edit occupies [T, 2T).
        pbar = comfy.utils.ProgressBar(infer_steps * 2)
        z_inv, delta_z = directedit.invert(
            anima=unet,
            z_clean=z_clean,
            embed_src=embed_src,
            embed_neg=embed_neg if invert_guidance != 1.0 else None,
            sigmas=sigmas,
            guidance_scale=invert_guidance,
            step_callback=lambda step, total: pbar.update_absolute(step),
        )
        z_edit = directedit.edit_forward(
            anima=unet,
            z_init=z_inv[0],
            delta_z=delta_z,
            embed_tar=embed_tar,
            embed_neg=embed_neg,
            sigmas=sigmas,
            guidance_scale=guidance_scale,
            embed_src=embed_src if t_inj > 0 else None,
            t_inj=t_inj,
            # t_inj_blocks=None -> directedit defaults to all-but-last (SD3.5 style).
            z_inv=z_inv if t_inj > 0 else None,
            step_callback=lambda step, total: pbar.update_absolute(infer_steps + step),
        )

        # Return a LATENT in raw VAE space to match the comfy convention
        # (samplers.py::process_latent_out is the equivalent step in the
        # KSampler pipeline). Wire into VAEDecode to render.
        z_edit_raw = model.model.process_latent_out(z_edit.to(dtype=dtype))
        logger.info("DirectEdit: returning edited latent %s", tuple(z_edit_raw.shape))
        return ({"samples": z_edit_raw.cpu()}, psi_src, psi_tar)


NODE_CLASS_MAPPINGS = {
    "AnimaDirectEdit": AnimaDirectEdit,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "AnimaDirectEdit": "Anima DirectEdit",
}
