[preview]
training_dir = "output/ckpt/sample"
inference_dir = "output/tests"
custom_dir = ""

[global]
output_root = "/home/scv/nvme0n1p1/训练器相关/anima缓存"
pretrained_model_name_or_path = "/home/scv/nvme0n1p1/ComfyUI/models/diffusion_models/anima/anima-preview3-base.safetensors"
qwen3 = "/home/scv/nvme0n1p1/ComfyUI/models/text_encoders/anima/anima_qwen_3_06b_base.safetensors"
vae = "/home/scv/nvme0n1p1/ComfyUI/models/vae/anima/anima_vae.safetensors"
