"""Immutable shim name tables for the config legacy facade.

Keeping these tables out of ``_legacy.py`` makes the compatibility shell smaller
and leaves ``_legacy`` focused on wiring installers.
"""

from __future__ import annotations

_COMMON_SYNC_NAMES = (
    "ROOT",
    "CONFIGS_DIR",
)

_COMMON_SHIM_NAMES = (
    "_auto_data_dir_for_key",
    "_bool_value",
    "_derived_data_dir",
    "_display_path",
    "_is_builtin_default_data_dir",
    "_load",
    "_nonnegative_float",
    "_nonnegative_int",
    "_positive_float",
    "_positive_int",
    "_positive_int_or_none",
    "_resolve_project_path",
    "_safe_config_subdir",
    "_safe_resolve",
)

_PREFLIGHT_SHIM_SYNC_NAMES = (
    "ROOT",
    "CONFIGS_DIR",
    "GUI_METHODS_DIR",
    "IMPORTED_CONFIGS_DIR",
    "PRESETS_FILE",
    "WEB_FILE_GROUPS_FILE",
    "WEB_USER_LOCKS_FILE",
    "DATASET_PRESETS_DIR",
    "resolve_output_root",
    "_display_settings_path",
    "save_raw_file",
    "load_raw_file",
    "delete_raw_file",
    "patch_raw_file_values",
    "preview_raw_file_patch",
    "get_config_file_meta",
    "list_config_file_groups",
    "move_config_file_to_group",
    "_inspect_network_weight",
    "LOGGER",
    "_display_path",
    "_resolve_project_path",
    "_is_blank_output_name",
    "_dataset_config_path_from_cfg",
    "_bool_value",
    "_positive_int_or_none",
    "_safe_resolve",
    "_normalize_config_rel_path",
    "apply_auto_data_dirs",
    "load_merged_config",
    "_dataset_rows_for_estimate",
    "_normalize_path_pattern",
    "_dataset_image_files",
    "_caption_detection_counts_text",
    "_normalize_trigger_clone",
    "_count_source_images",
    "_nl_tag_mix_enabled",
    "_nl_tag_mix_caption_counts",
)

_PREFLIGHT_SHIM_NAMES = (
    "preflight_training_config",
    "_load_training_config_for_web_run",
    "_config_file_path",
    "is_web_runtime_config",
    "training_sample_sampler_status",
    "apply_global_model_path_defaults",
    "_check_training_images",
    "_check_dataset_source_paths",
    "_check_dataset_bucket_settings",
    "_check_dataset_paths",
    "_check_cache_sidecars",
)

# Private helpers stay available on the legacy module but are not part of the
# public shim map / __all__-style contract. `_inspect_network_weight` is wired
# separately in `_legacy.py` because it forwards to `_inspect_network_weight_impl`.
_PREFLIGHT_PRIVATE_HELPER_NAMES = (
    "_check_network_weights",
    "_check_training_sample_config",
    "_config_path_from_display_path",
    "_is_allowed_training_config_path",
    "_is_web_runtime_config_tree",
    "_is_output_run_snapshot_config",
    "_has_web_runtime_dirs",
    "_looks_like_web_runtime_config",
    "_check_web_preprocess_environment",
    "_web_python_executable",
    "_check_cache_sidecar_pattern",
)

_MERGE_SHIM_SYNC_NAMES = (
    "ROOT",
    "CONFIGS_DIR",
    "GUI_METHODS_DIR",
    "IMPORTED_CONFIGS_DIR",
    "PRESETS_FILE",
    "WEB_FILE_GROUPS_FILE",
    "WEB_USER_LOCKS_FILE",
    "DATASET_PRESETS_DIR",
    "DEFAULT_MAX_TRAIN_STEPS",
    "resolve_output_root",
    "_display_settings_path",
    "LOGGER",
)

_MERGE_SHIM_NAMES = (
    "list_methods",
    "list_variants",
    "list_all_variants",
    "list_presets",
    "load_merged_config",
    "suggest_data_dirs",
    "suggest_dataset_dirs",
    "apply_auto_data_dirs",
)

_MERGE_PRIVATE_HELPER_NAMES = (
    "_builtin_variants_by_family",
    "_read_variant_metadata",
    "_legacy_exact_variant_for_method",
    "_custom_gui_variants",
)

_OUTPUT_RUNS_SHIM_SYNC_NAMES = (
    "ROOT",
    "CONFIGS_DIR",
    "GUI_METHODS_DIR",
    "IMPORTED_CONFIGS_DIR",
    "PRESETS_FILE",
    "WEB_FILE_GROUPS_FILE",
    "WEB_USER_LOCKS_FILE",
    "DATASET_PRESETS_DIR",
    "resolve_output_root",
    "_display_settings_path",
    "save_raw_file",
    "get_config_file_meta",
    "list_config_file_groups",
    "move_config_file_to_group",
    "LOGGER",
)

_OUTPUT_RUNS_LEGACY_HELPER_NAMES = (
    "_output_run_summary",
    "_output_run_config_path",
    "_normalize_output_run_save_as_path",
    "_safe_mtime",
    "_format_file_time",
)

_OUTPUT_RUNS_SHIM_NAMES = (
    "list_output_runs",
    "load_output_run_config",
    "save_output_run_config_as",
    "_resolve_output_run_dir",
    "_normalize_output_run_name",
)

_ESTIMATION_SHIM_SYNC_NAMES = (
    "ROOT",
    "CONFIGS_DIR",
    "GUI_METHODS_DIR",
    "IMPORTED_CONFIGS_DIR",
    "PRESETS_FILE",
    "WEB_FILE_GROUPS_FILE",
    "WEB_USER_LOCKS_FILE",
    "DATASET_PRESETS_DIR",
    "DEFAULT_MAX_TRAIN_STEPS",
    "resolve_output_root",
    "_display_settings_path",
    "LOGGER",
    "_load_training_config_for_web_run",
    "_normalize_config_rel_path",
    "_dataset_rows_for_estimate",
    "_resolve_project_path",
    "_display_path",
    "_positive_int",
    "_positive_float",
    "_nonnegative_int",
    "_bool_value",
    "_normalize_nl_tag_mix",
    "_normalize_trigger_clone",
    "_normalize_path_pattern",
    "_nl_tag_mix_available_count",
    "_count_source_images",
    "_count_images",
)

_ESTIMATION_SHIM_NAMES = (
    "estimate_training_steps",
)

_DATASET_SHIM_SYNC_NAMES = (
    "ROOT",
    "CONFIGS_DIR",
    "GUI_METHODS_DIR",
    "IMPORTED_CONFIGS_DIR",
    "PRESETS_FILE",
    "WEB_FILE_GROUPS_FILE",
    "WEB_USER_LOCKS_FILE",
    "DATASET_PRESETS_DIR",
    "resolve_output_root",
    "_display_settings_path",
    "save_raw_file",
    "load_raw_file",
    "delete_raw_file",
    "patch_raw_file_values",
    "preview_raw_file_patch",
    "get_config_file_meta",
    "list_config_file_groups",
    "move_config_file_to_group",
    "_inspect_network_weight",
    "LOGGER",
)

_DATASET_SHIM_NAMES = (
    "list_dataset_presets",
    "diagnose_dataset_presets",
    "load_dataset_preset",
    "save_dataset_preset",
    "save_dataset_preset_as",
    "import_dataset_preset",
    "delete_dataset_preset",
    "apply_dataset_preset_to_training_config",
    "list_dataset_preset_images",
    "resolve_dataset_preview_image",
    "load_dataset_editor",
    "save_dataset_editor",
    "_dataset_config_path_from_cfg",
    "_dataset_rows_for_estimate",
    "_dataset_rows_from_config",
    "_normalize_dataset_rows",
    "_normalize_dataset_defaults",
    "_dataset_preset_summary",
    "_dataset_preset_groups_for_ui",
    "_is_dataset_group_for_ui",
    "_dataset_summary_from_rows",
    "_normalize_nl_tag_mix",
    "_normalize_trigger_clone",
    "_normalize_path_pattern",
    "_build_dataset_config_doc",
    "_nl_tag_mix_caption_source",
    "_nl_tag_mix_image_files",
    "_classify_nl_tag_caption_text",
    # Private helpers still exposed via legacy compatibility surface.
    "_is_allowed_dataset_config_path",
    "_dataset_config_rel_path",
    "_training_config_rel_path",
    "_single_dataset_config_from_cfg",
    "_dataset_defaults_from_config",
    "_dataset_defaults_from_dataset",
    "_normalize_dataset_row_settings",
    "_fill_missing_dataset_row_settings",
    "_normalize_preprocess_dataset_settings",
    "_trigger_clone_should_persist",
    "_nl_tag_mix_enabled",
    "_preprocess_settings_from_custom_attributes",
    "_preprocess_settings_for_runtime_attrs",
    "_dataset_row_settings",
    "_first_dataset_settings",
    "_first_dataset_value",
    "_dataset_path_value",
    "_list_dataset_image_files",
    "_dataset_image_preview_meta",
    "_dataset_image_dimensions",
    "_dataset_caption_meta",
    "_caption_source_mode_label",
    "_caption_extension_for_detected_mode",
    "_format_caption_preview_text",
    "_dataset_caption_detection_summary",
    "_caption_detection_counts_text",
    "_dataset_preview_empty_message",
    "_safe_file_stem",
    "_dataset_image_files",
    "_count_images",
    "_count_source_images",
    "_dataset_num_repeats",
    "_nl_tag_mix_available_count",
    "_nl_tag_mix_caption_path_and_text",
    "_nl_tag_mix_caption_counts",
)

_SAMPLE_PROMPTS_SHIM_SYNC_NAMES = (
    "ROOT",
    "CONFIGS_DIR",
    "GUI_METHODS_DIR",
    "IMPORTED_CONFIGS_DIR",
    "PRESETS_FILE",
    "WEB_FILE_GROUPS_FILE",
    "WEB_USER_LOCKS_FILE",
    "DEFAULT_SAMPLE_PROMPTS_FILE",
    "DATASET_PRESETS_DIR",
    "resolve_output_root",
    "_display_settings_path",
    "LOGGER",
)

_SAMPLE_PROMPTS_SHIM_NAMES = (
    "load_sample_prompts_file",
    "save_sample_prompts_file",
    "_normalize_prompt_file_path",
    "_sample_prompts_path_for_config",
)

_FILE_GROUPS_SHIM_SYNC_NAMES = (
    "ROOT",
    "CONFIGS_DIR",
    "GUI_METHODS_DIR",
    "IMPORTED_CONFIGS_DIR",
    "PRESETS_FILE",
    "WEB_FILE_GROUPS_FILE",
    "WEB_USER_LOCKS_FILE",
    "DATASET_PRESETS_DIR",
    "resolve_output_root",
    "_display_settings_path",
    "save_raw_file",
    "load_raw_file",
    "delete_raw_file",
    "patch_raw_file_values",
    "preview_raw_file_patch",
    "_inspect_network_weight",
    "LOGGER",
)

_FILE_GROUPS_SHIM_NAMES = (
    "set_user_file_lock",
    "set_user_group_lock",
    "create_config_file_group",
    "rename_config_file_group",
    "delete_config_file_group",
    "reorder_config_file_group",
    "move_config_file_to_group",
    "place_config_file_in_group",
    "place_config_file_group",
    "reorder_config_file_in_group",
    "restore_system_presets",
    "list_config_files",
    "list_config_file_groups",
    "export_config_file_group_archive",
    "get_config_file_meta",
    "_load_config_file_group_specs",
    "_save_config_file_group_specs",
    "_normalize_config_file_group_kind_filter",
    "_normalize_config_rel_path",
    "_normalize_dataset_preset_path",
    "_is_dataset_preset_readonly",
    "_is_user_locked",
    "_is_user_group_locked",
    "_load_user_locks",
    "_save_user_locks",
    "_lock_reason_message",
    "_lock_reason_label",
    "_get_config_file_group",
    "_config_group_kind",
    "_normalize_group_id",
    "_safe_archive_name",
    "_unique_archive_member_name",
    "_config_method_name_for_path",
    "_infer_config_file_group",
    "_strip_configs_prefix",
    "_sort_config_file_group_specs_for_display",
    "_build_config_file_group",
    "_glob_config_files",
    "_default_config_file_group_specs",
    "_group_defaults",
    "_find_config_group_spec",
    "_new_user_config_group_spec",
    "_move_orphaned_config_files_to_fallback_groups",
    "_config_file_is_covered_by_specs",
    "_fallback_config_group_spec",
    "_is_user_managed_group",
    "_is_fixed_config_group",
    "_is_deletable_config_group",
    "_is_renamable_config_group",
    "_is_move_target_group",
    "_is_sortable_config_group_for_place",
    "_place_index",
    "_lockable_group_ids",
    "_unique_group_id",
    "_slugify_group_label",
    "_normalize_group_label",
    "_group_patterns_include_file",
    "_is_system_preset_path",
    "_is_system_locked_path",
    "_list_system_preset_files",
    "_read_git_head_file",
    "_backup_relative_path",
    "_string_list",
    "_config_group_path_list",
)

_RAW_FILES_SHIM_SYNC_NAMES = (
    "ROOT",
    "CONFIGS_DIR",
    "GUI_METHODS_DIR",
    "IMPORTED_CONFIGS_DIR",
    "PRESETS_FILE",
    "WEB_FILE_GROUPS_FILE",
    "WEB_USER_LOCKS_FILE",
    "DATASET_PRESETS_DIR",
    "resolve_output_root",
    "_display_settings_path",
    "get_config_file_meta",
    "list_config_file_groups",
    "move_config_file_to_group",
    "_inspect_network_weight",
    "LOGGER",
)

_RAW_FILES_LEGACY_HELPER_NAMES = (
    "_safe_resolve",
    "_normalize_config_rel_path",
    "_load_user_locks",
    "_save_user_locks",
    "_lock_reason_message",
)

_RAW_FILES_FACADE_HELPER_NAMES = (
    "get_config_file_meta",
    "list_config_file_groups",
    "move_config_file_to_group",
)

_RAW_FILES_SHIM_NAMES = (
    "load_raw_file",
    "save_raw_file",
    "delete_raw_file",
    "patch_raw_file_values",
    "preview_raw_file_patch",
    "_prepare_raw_file_patch",
    "_restore_dataset_config_after_failed_train_patch",
    "_patch_toml_top_level",
    "_is_spd_patch_target",
    "_remove_retired_top_level_fields",
    "_normalize_patch_value",
    "_normalize_saved_raw_config_content",
    "_normalize_saved_raw_config_content_with_changed_keys",
    "_is_blank_output_name",
)
